# mkdocs.yml

site_name: 'Analytics'
site_url: https://idea-technology-it.github.io/docs-idea/
site_description: Documentação para o projeto Idea Business Analytics
site_author: rafaelmedeirosnobre@gmail.com
# Copyright
copyright: Copyright &copy; 2024 - 2024 Idea Technology

# Configuration
theme:
  language: pt-BR 
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - navigation.footer
    - content.tooltips
  palette:
  - scheme: default
    primary: 'black'
    accent: 'yellow'
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - scheme: slate
    primary: 'black'
    accent: 'yellow'
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  icon:
    logo: logo


# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
  # - git-committers:
  #     repository: IDEA-TECHNOLOGY-IT/docs-idea_finance
  #     branch: main
  - glightbox


# Configurações de extra CSS (opcional)
extra_css:
  - 'stylesheets/fonts.css'
  - 'stylesheets/root.css'
  - 'stylesheets/carrousel.css'
  - 'stylesheets/home.css'

# Configurações de extra JavaScript (opcional)
extra_javascript:
  - 'javascripts/carrousel.js'
  - 'javascripts/home.js'

# Configurações para Markdown
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Configurações de Favicon (opcional)
extra:
  generator: false
  social:
    - icon: fontawesome/regular/envelope
      link: comercial@ideatechnology.com.br
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/idea-technology/posts/?feedView=all

# Watch custom files for changes
watch:
  - docs
  - overrides
  
nav:
- Início: index.md
- Documentação:
  - BI Idea Sales:
    - faturamento/ficha_tecnica.md
    - faturamento/intro.md
    - faturamento/indicadores_faturamento.md
    - faturamento/painel_faturamento.md
    - faturamento/vendas.md
    - faturamento/devolucoes.md
    - faturamento/faturamento_liquido.md
    - faturamento/cmv.md
    - faturamento/itens.md
    - faturamento/indicadores.md
  - BI Idea Finance: 
    - financeiro/ficha_tecnica.md
    - financeiro/intro.md
    - financeiro/indicadores_caixas.md
    - financeiro/painel_financeiro.md
    - financeiro/contas_a_receber.md
    - financeiro/contas_a_pagar.md
    - financeiro/inadimplencia.md
    - financeiro/pagamentos_vencidos.md
    - financeiro/painel_recebimentos_realizados.md
    - financeiro/painel_pagamentos_realizados.md
    - financeiro/fluxo_caixa.md
    - financeiro/saldo_contas.md
    - financeiro/detalhamento.md
  - BI Idea Accounting:
    - contabilidade/ficha_tecnica.md
    - contabilidade/intro.md
    - contabilidade/indicadores_contabeis.md
    - contabilidade/painel_contabil.md
    - contabilidade/receita_bruta.md
    - contabilidade/custos_e_despesas.md
    - contabilidade/lucro_liquido.md
    - contabilidade/ebitda.md
    - contabilidade/indicadores.md
    - contabilidade/regra_dos_40.md
    - contabilidade/dre.md
- Demonstrações:
  - faturamento/demo.md
  - financeiro/demo.md
  - contabilidade/demo.md
